experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_elliot.tsv
    test_path: ../data/{0}/test_elliot.tsv
  dataset: amazon-book
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.ContextGNN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        validation_rate: 20
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: 0.001
      epochs: 20
      factors: 128
      batch_size: 128
      n_layers: 4
      aggr: sum
      channels: 128
      max_steps: 2000
      neigh: (16,16,8,8)
      seed: 42