experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}_sub10/train_elliot.tsv
    test_path:  ../data/{0}_sub10/test_elliot.tsv
  dataset: amazon-book
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.ContextGNN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: True
        validation_rate: 1
        validation_metric: nDCG@20
        restore: False
        write_best_iterations: True
      
      # TRAINING
      epochs: 3
      max_steps: 600
      lr: 0.001
      batch_size: 256 # Increase if GPU allows it
      seed: 42
      
      # ARCHITECTURE
      n_layers: 3
      aggr: sum
      factors: 128
      channels: 128
      neigh: (32,16,8)